/**
 * Created by AbhishekG on 7/12/2016.
 */

import {onetomany, manytoone, manytomany} from 'nodedata/core/decorators';
import {field, document} from 'nodedata/mongoose/decorators';
import {Types} from 'mongoose';
import {Strict} from 'nodedata/mongoose/enums';

@document({ name: 'rsDSL', strict: Strict.false })
export class RSDSLModel {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    dsl: string;

}
export default RSDSLModel;